# -- Stage 1: Build --
FROM node:lts as builder

# Setup workspace
RUN mkdir /app
WORKDIR /app

RUN yarn set version classic

# Setup dependencies management
COPY package.json ./
COPY yarn.lock ./
COPY prisma ./prisma/

# Install dependencies 
RUN yarn install

# Copy all source code
COPY . .

# Generate types and compile
RUN yarn generate
RUN yarn build

# -- Stage 2: Deploy --
FROM node:lts

# Grab the important files
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/yarn.lock ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma

# Install production only dependencies
RUN yarn install --production

# Set the Node.js environment
ENV NODE_ENV production

# Run prisma generate
RUN yarn generate

CMD [ "yarn", "start" ]
