FROM node:current-alpine3.11 as builder

RUN mkdir /app
WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
COPY prisma ./prisma/

RUN yarn install --network-concurrency 1 

COPY . .

FROM node:current-alpine3.11

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist

ENV NODE_ENV production

CMD [ "yarn", "start" ]
